version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4041:4040"
#    environment:
#      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark_streaming/:/opt/spark-data
    networks:
      - big-data-net
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./spark_streaming/:/opt/spark-data
    networks:
      - big-data-net
  twitter-socket-host:
    image: twitter-socket-stream
    container_name: twitter-socket-stream
    hostname: socket-host-dns
    depends_on:
      - spark-master
    ports:
      - "5555:5555"
    #volumes:
    #  - ./examples/python/socket-host/:/opt/twitter
    networks:
      - big-data-net
  mongo-db:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME = admin-user
#      - MONGO_INITDB_ROOT_PASSWORD = admin-password
#      - MONGO_INITDB_DATABASE = admin
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
      - ~/mongo/data:/data/db # saves mongo stuff locally
    ports:
      - "27017:27017"
    networks:
      - big-data-net
#  spark-history-server:
#    image: bde2020/spark-history-server:3.3.0-hadoop3.3
#    container_name: spark-history-server
#    depends_on:
#      - spark-master
#    ports:
#      - "18081:18081"
#    volumes:
#      - ./examples/python/:/opt/spark-data

networks:
# Network for socket connection
  big-data-net:
# Bridge Driver: Default network driver
    driver: bridge
