apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: big-data
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: git.haw-hamburg.de:5005/acg569/big-data/mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: spark-data

      imagePullSecrets:
        - name: haw
      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: speicher-big-data