apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: big-data
  labels:
    app: streaming
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
        - name: spark-master
          image: git.haw-hamburg.de:5005/acg569/big-data/spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 4041
          env:
            - name: SERVER_ADDRESS
              value: twitter-host-service
          volumeMounts:
            - mountPath: "/opt/spark-data"
              name: spark-data


#        - name: twitter-socket-stream
 #        image: git.haw-hamburg.de:5005/acg569/big-data/twitter-socket-stream
  #        env:
   #         - name: SERVER_ADDRESS
    #          value: twitter-host-service
     #     ports:
      #      - containerPort: 5555
       #   volumeMounts:
        #    - mountPath: "/opt/spark-data"
         #     name: spark-data

      imagePullSecrets:
        - name: haw
      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: speicher-big-data