kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  namespace: big-data
  labels:
    service: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi