kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: speicher-big-data
  namespace: big-data
  labels:
    service: bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi