kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-storage
  namespace: big-data
  labels:
    service: worker-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi