version: '3'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME = admin-user
#      - MONGO_INITDB_ROOT_PASSWORD = admin-password
#      - MONGO_INITDB_DATABASE = admin
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
      - ~/mongo/data:/data/db # saves mongo stuff locally
    ports:
      - "27017:27017"