apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata
  namespace: big-data
  labels:
    service: bigdata
spec:
  selector:
    matchLabels:
      service: bigdata
  template:
    metadata:
      labels:
        service: bigdata
    spec:
#      hostNetwork: true
      containers:
        - name: spark-master
          image: git.haw-hamburg.de:5005/acg569/big-data/spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 4041
          volumeMounts:
            - mountPath: "/opt/spark-data"
              name: spark-data


        - name: spark-worker-1
          image: git.haw-hamburg.de:5005/acg569/big-data/spark-worker
          env:
            - name: SPARK_MASTER
              value: localhost:7077 #TODO container name
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: "/opt/spark-data"
              name: spark-data


        - name: twitter-socket-stream
          image: git.haw-hamburg.de:5005/acg569/big-data/twitter-socket-stream
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: "/opt/spark-data"
              name: spark-data


        - name: mongo-db
          image: git.haw-hamburg.de:5005/acg569/big-data/mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: spark-data
          ports:
            - containerPort: 27017


      imagePullSecrets:
        - name: haw
      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: speicher-big-data

---
apiVersion: v1
kind: Service
metadata:
  name: bigdata
  namespace: big-data
  labels:
    service: bigdata
spec:
  ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    service: bigdata
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-host-service
  namespace: big-data
  labels:
    service: bigdata
spec:
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      name: http
  selector:
    app: server
  type: ClusterIP